name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        npm config set @isaaceliape:registry https://registry.npmjs.org/
        npm config set //registry.npmjs.org/:_authToken=
        npm ci
      
    - name: Run lint
      run: npm run lint